[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]
optimizer = true
optimizer_runs = 200
via_ir = true
gas_price          = 100000000000   # 100 gwei in wei
priority_gas_price = 2000000000     # 2 gwei in wei